#
# sample config.yml for Docker registry
#
# To use, complete the following fields:
# storage/s3:bucket: The name of the bucket for sotring images, e.g., prod.docker.registry.sagebase.org
# auth/token/realm: The Synapse auth' endpoint, e.g., https://repo-prod.prod.sagebase.org/docker/v1/bearerToken
# auth/token/service: docker.synapse.org or, for dev', dev-docker-registry.dev.sagebase.org
# notification/endpoints/url:  The Synapse endpoint for notifications. See https://rest-docs.synapse.org/rest/POST/events.html
# notification/endpoints/headers/Authorization: A name/pwd pair used to authenticate with Synapse when sending events, in Basic Authorization format.
#
# Additional guidance here: https://distribution.github.io/distribution/about/deploying/

version: 0.1
log:
    level: info
    formatter: text
    fields:
        service: registry
http:
    addr: :443
    tls:
        certificate: /etc/docker/registry/ssl/public.crt
        key: /etc/docker/registry/ssl/privatekey.pem

storage:
    cache:
        layerinfo: inmemory
    s3:
        region: us-east-1
        bucket:
        encrypt: true
        secure: true
        v4auth: true
        chunksize: 104857600
        rootdirectory: /

auth:
    token:
        realm: https://repo-prod.prod.sagebase.org/docker/v1/bearerToken
        service: docker.synapse.org
        issuer: www.synapse.org
        rootcertbundle: /etc/docker/registry/cert.pem

notifications:
    endpoints:
    - name: Synapse
      disabled: false
      url: https://repo-prod.prod.sagebase.org/dockerRegistryListener/v1/events
      headers:
          Authorization:
              - Basic base64-encoded-pair
      timeout: 1m
      threshold: 1
      backoff: 30s
