#!/bin/sh

# Inject http_secret into config.yml
# The value is taken from the environment variable, `http_secret` which,
# during ECS deployment comes from the AWS Secrets Manager.
sed -i "s|http_secret|$http_secret|g" /etc/docker/registry/config.yml

# Inject notification listener authorization credentials into config.yml
# The value is taken from the environment variable, `notification_auth` which
# during ECS deployment comes from the AWS Secrets Manager.
sed -i "s|notification_auth|$notification_auth|g" /etc/docker/registry/config.yml

# Inject api_gateway_url into config.yml
# The value is taken from the environment variable, `api_gateway_url` which
# is generated by CDK during ECS deployment.
# Note we can't use the standard '/' for the sed separator because
# the URL contains that character.
sed -i "s|api_gateway_url|$api_gateway_url|g" /etc/docker/registry/config.yml

# Inject bucket name into config.yml
# The value is taken from the environment variable, `BUCKET_NAME` which,
# during ECS deployment comes from the cdk.json file.
sed -i "s|bucket_name|$BUCKET_NAME|g" /etc/docker/registry/config.yml

# this assumed a particular start-up for the container registry
# if the command changes in future versions, this will have to be updated too
/entrypoint.sh /etc/docker/registry/config.yml
