
name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

concurrency: ci-${{ github.ref }}

env:
  branch: ${{ github.head_ref || github.ref_name }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Static Analysis
        uses: pre-commit/action@v3.0.0

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run unit tests
        run: python -m pytest tests/ -s -v

  # make sure tests pass for both dev and prod stacks
  synth-test:
    needs: tests
    strategy:
      matrix:
        stack: ['dev', 'prod']
    uses: "./.github/workflows/synth-test.yml"
    with:
      CONTEXT: ${{ matrix.stack }}

  build-registry-container:
    needs: [tests, synth-test]
    if: env.branch == 'dev' || env.branch == 'prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create self-signed cert
        run: >
          openssl req -x509 -days 3650 -newkey rsa:2048 -sha256
          -nodes -keyout privatekey.pem -out certificate.pem
          -subj "/C=US/ST=Seattle/L=WA/O=SageBionetworks/OU=IT/CN=synapse.org"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.4.0
        with:
          context: .
          build-args: stack=$env.branch
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  cdk-deploy-dev:
    if: env.branch == 'dev'
    needs: [tests, synth-test, build-registry-container]
    uses: "./.github/workflows/aws-deploy.yml"
    secrets: inherit
    with:
      CONTEXT: $env.branch
      ROLE_TO_ASSUME: arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-docker-registry

  cdk-deploy-prod:
    if: env.branch == 'prod'
    needs: [tests, synth-test, build-registry-container]
    uses: "./.github/workflows/aws-deploy.yml"
    secrets: inherit
    with:
      CONTEXT: $env.branch
      ROLE_TO_ASSUME: arn:aws:iam::325565585839:role/sagebase-github-oidc-sage-bionetworks-synapse-docker-registry
